name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-DEV:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'pedroalves616.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo deploy dev
        
  deploy-HMG:
    runs-on: ubuntu-latest
    environment:
      name: HMG
      url: 'pedroalves616.com'
    needs: deploy-DEV
    steps:
      - name: Run a one-line script
        run: echo deploy HMG
        
  deploy-PRD:
    runs-on: ubuntu-latest
    environment:
      name: PRD
      url: 'pedroalves616.com'
    needs: deploy-DEV
    steps:
      - name: Run a one-line script
        run: echo deploy PRD
